In [1]:
import numpy as np

In [2]:
a=np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])

In [3]:
a[0,3]

3

In [4]:
print(a[0])

[0 1 2 3 4 5]


In [5]:
a.shape

(2, 6)

In [6]:
a.size

12

In [7]:
a.dtype

dtype('int32')

In [8]:
a[0,1]=12

In [9]:
a

array([[ 0, 12,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [10]:
zeros = np.zeros((2,5))

In [11]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
range = np.arange(15)

In [13]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
linspace = np.linspace(1,5,10)  # linspace gives 10 equally spaced elements between 1-5

In [15]:
linspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [16]:
emp = np.empty((4,6))

In [17]:
emp #gives empty array with random values

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.24610994e-306, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 1.39071445e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307, 1.02359984e-306],
       [1.33510679e-306, 2.22522597e-306, 6.23053614e-307,
        1.33511562e-306, 6.89805151e-307, 8.90111708e-307]])

In [18]:
emp_like = np.empty_like(linspace)

In [19]:
emp_like

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [20]:
ide = np.identity(5)

In [21]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
c = np.arange(99)

In [23]:
c.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [24]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
c = c.reshape(3,33)

In [26]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [27]:
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [28]:
x=[[1,2,3],[1,5,6],[7,8,9]]

In [29]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [1, 5, 6],
       [7, 8, 9]])

In [30]:
ar.sum(axis=0)

array([ 9, 15, 18])

In [31]:
ar.sum(axis=1)

array([ 6, 12, 24])

In [32]:
ar.T    # Transpose of ar

array([[1, 1, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [33]:
ar.flat

In [34]:
for item in ar.flat:
    print(item)

1
2
3
1
5
6
7
8
9


In [35]:
ar.ndim # gives dimension

2

In [36]:
ar.nbytes   # Storage consumed by the array ar

36

In [37]:
one = np.array([1,2,3,45,6])    # Creating 1D array

In [38]:
one.argmax()    # Gives the index of maximum input

3

In [39]:
one.argsort()   # Sorts the array as per index

array([0, 1, 2, 4, 3], dtype=int64)

In [40]:
ar  # Bringing back previously made array

array([[1, 2, 3],
       [1, 5, 6],
       [7, 8, 9]])

In [41]:
ar.argmin()

0

In [42]:
ar.argmax()

8

In [43]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [44]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [45]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [46]:
ar.ravel()

array([1, 2, 3, 1, 5, 6, 7, 8, 9])

In [47]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [1],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [48]:
ar+ar.T

array([[ 2,  3, 10],
       [ 3, 10, 14],
       [10, 14, 18]])

In [49]:
sq = np.array([1,4,9])

In [50]:
np.sqrt(sq)

array([1., 2., 3.])

In [51]:
ar

array([[1, 2, 3],
       [1, 5, 6],
       [7, 8, 9]])

In [52]:
np.where(ar>7)

(array([2, 2], dtype=int64), array([1, 2], dtype=int64))

In [53]:
np.count_nonzero(ar)

9